# This file stores configurations for your Shopify app.
scopes = "write_products,read_products,read_orders,write_orders"
#read_orders,write_orders,write_own_subscription_contracts,read_own_subscription_contracts,read_customer_payment_methods,read_all_orders"
